project_name: teleskop
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - main: .
    binary: teleskop
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
      - arm64