// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetISCSIQualifiedNameRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetISCSIQualifiedNameRequest) Reset()         { *m = GetISCSIQualifiedNameRequest{} }
func (m *GetISCSIQualifiedNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetISCSIQualifiedNameRequest) ProtoMessage()    {}
func (*GetISCSIQualifiedNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *GetISCSIQualifiedNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetISCSIQualifiedNameRequest.Unmarshal(m, b)
}
func (m *GetISCSIQualifiedNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetISCSIQualifiedNameRequest.Marshal(b, m, deterministic)
}
func (m *GetISCSIQualifiedNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetISCSIQualifiedNameRequest.Merge(m, src)
}
func (m *GetISCSIQualifiedNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetISCSIQualifiedNameRequest.Size(m)
}
func (m *GetISCSIQualifiedNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetISCSIQualifiedNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetISCSIQualifiedNameRequest proto.InternalMessageInfo

type GetIPTablesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIPTablesRequest) Reset()         { *m = GetIPTablesRequest{} }
func (m *GetIPTablesRequest) String() string { return proto.CompactTextString(m) }
func (*GetIPTablesRequest) ProtoMessage()    {}
func (*GetIPTablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *GetIPTablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIPTablesRequest.Unmarshal(m, b)
}
func (m *GetIPTablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIPTablesRequest.Marshal(b, m, deterministic)
}
func (m *GetIPTablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIPTablesRequest.Merge(m, src)
}
func (m *GetIPTablesRequest) XXX_Size() int {
	return xxx_messageInfo_GetIPTablesRequest.Size(m)
}
func (m *GetIPTablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIPTablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIPTablesRequest proto.InternalMessageInfo

type SetupDefaultSecurityGroupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupDefaultSecurityGroupRequest) Reset()         { *m = SetupDefaultSecurityGroupRequest{} }
func (m *SetupDefaultSecurityGroupRequest) String() string { return proto.CompactTextString(m) }
func (*SetupDefaultSecurityGroupRequest) ProtoMessage()    {}
func (*SetupDefaultSecurityGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *SetupDefaultSecurityGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupDefaultSecurityGroupRequest.Unmarshal(m, b)
}
func (m *SetupDefaultSecurityGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupDefaultSecurityGroupRequest.Marshal(b, m, deterministic)
}
func (m *SetupDefaultSecurityGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupDefaultSecurityGroupRequest.Merge(m, src)
}
func (m *SetupDefaultSecurityGroupRequest) XXX_Size() int {
	return xxx_messageInfo_SetupDefaultSecurityGroupRequest.Size(m)
}
func (m *SetupDefaultSecurityGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupDefaultSecurityGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetupDefaultSecurityGroupRequest proto.InternalMessageInfo

type AddSecurityGroupRequest struct {
	Interface            string   `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	IpAddress            string   `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	MacAddress           string   `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSecurityGroupRequest) Reset()         { *m = AddSecurityGroupRequest{} }
func (m *AddSecurityGroupRequest) String() string { return proto.CompactTextString(m) }
func (*AddSecurityGroupRequest) ProtoMessage()    {}
func (*AddSecurityGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *AddSecurityGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSecurityGroupRequest.Unmarshal(m, b)
}
func (m *AddSecurityGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSecurityGroupRequest.Marshal(b, m, deterministic)
}
func (m *AddSecurityGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSecurityGroupRequest.Merge(m, src)
}
func (m *AddSecurityGroupRequest) XXX_Size() int {
	return xxx_messageInfo_AddSecurityGroupRequest.Size(m)
}
func (m *AddSecurityGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSecurityGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSecurityGroupRequest proto.InternalMessageInfo

func (m *AddSecurityGroupRequest) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *AddSecurityGroupRequest) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *AddSecurityGroupRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

type AddBridgeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBridgeRequest) Reset()         { *m = AddBridgeRequest{} }
func (m *AddBridgeRequest) String() string { return proto.CompactTextString(m) }
func (*AddBridgeRequest) ProtoMessage()    {}
func (*AddBridgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}

func (m *AddBridgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBridgeRequest.Unmarshal(m, b)
}
func (m *AddBridgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBridgeRequest.Marshal(b, m, deterministic)
}
func (m *AddBridgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBridgeRequest.Merge(m, src)
}
func (m *AddBridgeRequest) XXX_Size() int {
	return xxx_messageInfo_AddBridgeRequest.Size(m)
}
func (m *AddBridgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBridgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBridgeRequest proto.InternalMessageInfo

func (m *AddBridgeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddVLANInterfaceRequest struct {
	VlanId               uint32   `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	ParentInterface      string   `protobuf:"bytes,2,opt,name=parent_interface,json=parentInterface,proto3" json:"parent_interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddVLANInterfaceRequest) Reset()         { *m = AddVLANInterfaceRequest{} }
func (m *AddVLANInterfaceRequest) String() string { return proto.CompactTextString(m) }
func (*AddVLANInterfaceRequest) ProtoMessage()    {}
func (*AddVLANInterfaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5}
}

func (m *AddVLANInterfaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddVLANInterfaceRequest.Unmarshal(m, b)
}
func (m *AddVLANInterfaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddVLANInterfaceRequest.Marshal(b, m, deterministic)
}
func (m *AddVLANInterfaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddVLANInterfaceRequest.Merge(m, src)
}
func (m *AddVLANInterfaceRequest) XXX_Size() int {
	return xxx_messageInfo_AddVLANInterfaceRequest.Size(m)
}
func (m *AddVLANInterfaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddVLANInterfaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddVLANInterfaceRequest proto.InternalMessageInfo

func (m *AddVLANInterfaceRequest) GetVlanId() uint32 {
	if m != nil {
		return m.VlanId
	}
	return 0
}

func (m *AddVLANInterfaceRequest) GetParentInterface() string {
	if m != nil {
		return m.ParentInterface
	}
	return ""
}

type AddInterfaceToBridgeRequest struct {
	Bridge               string   `protobuf:"bytes,1,opt,name=bridge,proto3" json:"bridge,omitempty"`
	Interface            string   `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddInterfaceToBridgeRequest) Reset()         { *m = AddInterfaceToBridgeRequest{} }
func (m *AddInterfaceToBridgeRequest) String() string { return proto.CompactTextString(m) }
func (*AddInterfaceToBridgeRequest) ProtoMessage()    {}
func (*AddInterfaceToBridgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{6}
}

func (m *AddInterfaceToBridgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddInterfaceToBridgeRequest.Unmarshal(m, b)
}
func (m *AddInterfaceToBridgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddInterfaceToBridgeRequest.Marshal(b, m, deterministic)
}
func (m *AddInterfaceToBridgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddInterfaceToBridgeRequest.Merge(m, src)
}
func (m *AddInterfaceToBridgeRequest) XXX_Size() int {
	return xxx_messageInfo_AddInterfaceToBridgeRequest.Size(m)
}
func (m *AddInterfaceToBridgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddInterfaceToBridgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddInterfaceToBridgeRequest proto.InternalMessageInfo

func (m *AddInterfaceToBridgeRequest) GetBridge() string {
	if m != nil {
		return m.Bridge
	}
	return ""
}

func (m *AddInterfaceToBridgeRequest) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

type AddVirtualMachineRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vcpus                uint32   `protobuf:"varint,2,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryKib            uint64   `protobuf:"varint,3,opt,name=memory_kib,json=memoryKib,proto3" json:"memory_kib,omitempty"`
	BootDevice           string   `protobuf:"bytes,4,opt,name=boot_device,json=bootDevice,proto3" json:"boot_device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddVirtualMachineRequest) Reset()         { *m = AddVirtualMachineRequest{} }
func (m *AddVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*AddVirtualMachineRequest) ProtoMessage()    {}
func (*AddVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{7}
}

func (m *AddVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddVirtualMachineRequest.Unmarshal(m, b)
}
func (m *AddVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (m *AddVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddVirtualMachineRequest.Merge(m, src)
}
func (m *AddVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_AddVirtualMachineRequest.Size(m)
}
func (m *AddVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddVirtualMachineRequest proto.InternalMessageInfo

func (m *AddVirtualMachineRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddVirtualMachineRequest) GetVcpus() uint32 {
	if m != nil {
		return m.Vcpus
	}
	return 0
}

func (m *AddVirtualMachineRequest) GetMemoryKib() uint64 {
	if m != nil {
		return m.MemoryKib
	}
	return 0
}

func (m *AddVirtualMachineRequest) GetBootDevice() string {
	if m != nil {
		return m.BootDevice
	}
	return ""
}

type ConnectBlockDeviceRequest struct {
	PortalAddresses      []string `protobuf:"bytes,1,rep,name=portal_addresses,json=portalAddresses,proto3" json:"portal_addresses,omitempty"`
	LunId                string   `protobuf:"bytes,2,opt,name=lun_id,json=lunId,proto3" json:"lun_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectBlockDeviceRequest) Reset()         { *m = ConnectBlockDeviceRequest{} }
func (m *ConnectBlockDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectBlockDeviceRequest) ProtoMessage()    {}
func (*ConnectBlockDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{8}
}

func (m *ConnectBlockDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectBlockDeviceRequest.Unmarshal(m, b)
}
func (m *ConnectBlockDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectBlockDeviceRequest.Marshal(b, m, deterministic)
}
func (m *ConnectBlockDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectBlockDeviceRequest.Merge(m, src)
}
func (m *ConnectBlockDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectBlockDeviceRequest.Size(m)
}
func (m *ConnectBlockDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectBlockDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectBlockDeviceRequest proto.InternalMessageInfo

func (m *ConnectBlockDeviceRequest) GetPortalAddresses() []string {
	if m != nil {
		return m.PortalAddresses
	}
	return nil
}

func (m *ConnectBlockDeviceRequest) GetLunId() string {
	if m != nil {
		return m.LunId
	}
	return ""
}

type AttachBlockDeviceRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SourceDevice         string   `protobuf:"bytes,2,opt,name=source_device,json=sourceDevice,proto3" json:"source_device,omitempty"`
	TargetDevice         string   `protobuf:"bytes,3,opt,name=target_device,json=targetDevice,proto3" json:"target_device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachBlockDeviceRequest) Reset()         { *m = AttachBlockDeviceRequest{} }
func (m *AttachBlockDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*AttachBlockDeviceRequest) ProtoMessage()    {}
func (*AttachBlockDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{9}
}

func (m *AttachBlockDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachBlockDeviceRequest.Unmarshal(m, b)
}
func (m *AttachBlockDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachBlockDeviceRequest.Marshal(b, m, deterministic)
}
func (m *AttachBlockDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachBlockDeviceRequest.Merge(m, src)
}
func (m *AttachBlockDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_AttachBlockDeviceRequest.Size(m)
}
func (m *AttachBlockDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachBlockDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachBlockDeviceRequest proto.InternalMessageInfo

func (m *AttachBlockDeviceRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AttachBlockDeviceRequest) GetSourceDevice() string {
	if m != nil {
		return m.SourceDevice
	}
	return ""
}

func (m *AttachBlockDeviceRequest) GetTargetDevice() string {
	if m != nil {
		return m.TargetDevice
	}
	return ""
}

type AttachInterfaceRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Bridge               string   `protobuf:"bytes,2,opt,name=bridge,proto3" json:"bridge,omitempty"`
	InboundAverage       uint32   `protobuf:"varint,3,opt,name=inbound_average,json=inboundAverage,proto3" json:"inbound_average,omitempty"`
	OutboundAverage      uint32   `protobuf:"varint,4,opt,name=outbound_average,json=outboundAverage,proto3" json:"outbound_average,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachInterfaceRequest) Reset()         { *m = AttachInterfaceRequest{} }
func (m *AttachInterfaceRequest) String() string { return proto.CompactTextString(m) }
func (*AttachInterfaceRequest) ProtoMessage()    {}
func (*AttachInterfaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{10}
}

func (m *AttachInterfaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachInterfaceRequest.Unmarshal(m, b)
}
func (m *AttachInterfaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachInterfaceRequest.Marshal(b, m, deterministic)
}
func (m *AttachInterfaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachInterfaceRequest.Merge(m, src)
}
func (m *AttachInterfaceRequest) XXX_Size() int {
	return xxx_messageInfo_AttachInterfaceRequest.Size(m)
}
func (m *AttachInterfaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachInterfaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachInterfaceRequest proto.InternalMessageInfo

func (m *AttachInterfaceRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AttachInterfaceRequest) GetBridge() string {
	if m != nil {
		return m.Bridge
	}
	return ""
}

func (m *AttachInterfaceRequest) GetInboundAverage() uint32 {
	if m != nil {
		return m.InboundAverage
	}
	return 0
}

func (m *AttachInterfaceRequest) GetOutboundAverage() uint32 {
	if m != nil {
		return m.OutboundAverage
	}
	return 0
}

func (m *AttachInterfaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StartVirtualMachineRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartVirtualMachineRequest) Reset()         { *m = StartVirtualMachineRequest{} }
func (m *StartVirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*StartVirtualMachineRequest) ProtoMessage()    {}
func (*StartVirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{11}
}

func (m *StartVirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartVirtualMachineRequest.Unmarshal(m, b)
}
func (m *StartVirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartVirtualMachineRequest.Marshal(b, m, deterministic)
}
func (m *StartVirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartVirtualMachineRequest.Merge(m, src)
}
func (m *StartVirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_StartVirtualMachineRequest.Size(m)
}
func (m *StartVirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartVirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartVirtualMachineRequest proto.InternalMessageInfo

func (m *StartVirtualMachineRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type DeleteBridgeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBridgeRequest) Reset()         { *m = DeleteBridgeRequest{} }
func (m *DeleteBridgeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBridgeRequest) ProtoMessage()    {}
func (*DeleteBridgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{12}
}

func (m *DeleteBridgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBridgeRequest.Unmarshal(m, b)
}
func (m *DeleteBridgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBridgeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBridgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBridgeRequest.Merge(m, src)
}
func (m *DeleteBridgeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBridgeRequest.Size(m)
}
func (m *DeleteBridgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBridgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBridgeRequest proto.InternalMessageInfo

func (m *DeleteBridgeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteVLANInterfaceRequest struct {
	VlanId               uint32   `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	ParentInterface      string   `protobuf:"bytes,2,opt,name=parent_interface,json=parentInterface,proto3" json:"parent_interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVLANInterfaceRequest) Reset()         { *m = DeleteVLANInterfaceRequest{} }
func (m *DeleteVLANInterfaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVLANInterfaceRequest) ProtoMessage()    {}
func (*DeleteVLANInterfaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{13}
}

func (m *DeleteVLANInterfaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVLANInterfaceRequest.Unmarshal(m, b)
}
func (m *DeleteVLANInterfaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVLANInterfaceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteVLANInterfaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVLANInterfaceRequest.Merge(m, src)
}
func (m *DeleteVLANInterfaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVLANInterfaceRequest.Size(m)
}
func (m *DeleteVLANInterfaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVLANInterfaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVLANInterfaceRequest proto.InternalMessageInfo

func (m *DeleteVLANInterfaceRequest) GetVlanId() uint32 {
	if m != nil {
		return m.VlanId
	}
	return 0
}

func (m *DeleteVLANInterfaceRequest) GetParentInterface() string {
	if m != nil {
		return m.ParentInterface
	}
	return ""
}

type DeleteInterfaceFromBridgeRequest struct {
	Bridge               string   `protobuf:"bytes,1,opt,name=bridge,proto3" json:"bridge,omitempty"`
	Interface            string   `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteInterfaceFromBridgeRequest) Reset()         { *m = DeleteInterfaceFromBridgeRequest{} }
func (m *DeleteInterfaceFromBridgeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteInterfaceFromBridgeRequest) ProtoMessage()    {}
func (*DeleteInterfaceFromBridgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{14}
}

func (m *DeleteInterfaceFromBridgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteInterfaceFromBridgeRequest.Unmarshal(m, b)
}
func (m *DeleteInterfaceFromBridgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteInterfaceFromBridgeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteInterfaceFromBridgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteInterfaceFromBridgeRequest.Merge(m, src)
}
func (m *DeleteInterfaceFromBridgeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteInterfaceFromBridgeRequest.Size(m)
}
func (m *DeleteInterfaceFromBridgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteInterfaceFromBridgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteInterfaceFromBridgeRequest proto.InternalMessageInfo

func (m *DeleteInterfaceFromBridgeRequest) GetBridge() string {
	if m != nil {
		return m.Bridge
	}
	return ""
}

func (m *DeleteInterfaceFromBridgeRequest) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

// response
type GetISCSIQualifiedNameResponse struct {
	Iqn                  string   `protobuf:"bytes,1,opt,name=iqn,proto3" json:"iqn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetISCSIQualifiedNameResponse) Reset()         { *m = GetISCSIQualifiedNameResponse{} }
func (m *GetISCSIQualifiedNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetISCSIQualifiedNameResponse) ProtoMessage()    {}
func (*GetISCSIQualifiedNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{15}
}

func (m *GetISCSIQualifiedNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetISCSIQualifiedNameResponse.Unmarshal(m, b)
}
func (m *GetISCSIQualifiedNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetISCSIQualifiedNameResponse.Marshal(b, m, deterministic)
}
func (m *GetISCSIQualifiedNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetISCSIQualifiedNameResponse.Merge(m, src)
}
func (m *GetISCSIQualifiedNameResponse) XXX_Size() int {
	return xxx_messageInfo_GetISCSIQualifiedNameResponse.Size(m)
}
func (m *GetISCSIQualifiedNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetISCSIQualifiedNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetISCSIQualifiedNameResponse proto.InternalMessageInfo

func (m *GetISCSIQualifiedNameResponse) GetIqn() string {
	if m != nil {
		return m.Iqn
	}
	return ""
}

type GetIPTablesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIPTablesResponse) Reset()         { *m = GetIPTablesResponse{} }
func (m *GetIPTablesResponse) String() string { return proto.CompactTextString(m) }
func (*GetIPTablesResponse) ProtoMessage()    {}
func (*GetIPTablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{16}
}

func (m *GetIPTablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIPTablesResponse.Unmarshal(m, b)
}
func (m *GetIPTablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIPTablesResponse.Marshal(b, m, deterministic)
}
func (m *GetIPTablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIPTablesResponse.Merge(m, src)
}
func (m *GetIPTablesResponse) XXX_Size() int {
	return xxx_messageInfo_GetIPTablesResponse.Size(m)
}
func (m *GetIPTablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIPTablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIPTablesResponse proto.InternalMessageInfo

type SetupDefaultSecurityGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupDefaultSecurityGroupResponse) Reset()         { *m = SetupDefaultSecurityGroupResponse{} }
func (m *SetupDefaultSecurityGroupResponse) String() string { return proto.CompactTextString(m) }
func (*SetupDefaultSecurityGroupResponse) ProtoMessage()    {}
func (*SetupDefaultSecurityGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{17}
}

func (m *SetupDefaultSecurityGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupDefaultSecurityGroupResponse.Unmarshal(m, b)
}
func (m *SetupDefaultSecurityGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupDefaultSecurityGroupResponse.Marshal(b, m, deterministic)
}
func (m *SetupDefaultSecurityGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupDefaultSecurityGroupResponse.Merge(m, src)
}
func (m *SetupDefaultSecurityGroupResponse) XXX_Size() int {
	return xxx_messageInfo_SetupDefaultSecurityGroupResponse.Size(m)
}
func (m *SetupDefaultSecurityGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupDefaultSecurityGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetupDefaultSecurityGroupResponse proto.InternalMessageInfo

type AddSecurityGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSecurityGroupResponse) Reset()         { *m = AddSecurityGroupResponse{} }
func (m *AddSecurityGroupResponse) String() string { return proto.CompactTextString(m) }
func (*AddSecurityGroupResponse) ProtoMessage()    {}
func (*AddSecurityGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{18}
}

func (m *AddSecurityGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSecurityGroupResponse.Unmarshal(m, b)
}
func (m *AddSecurityGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSecurityGroupResponse.Marshal(b, m, deterministic)
}
func (m *AddSecurityGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSecurityGroupResponse.Merge(m, src)
}
func (m *AddSecurityGroupResponse) XXX_Size() int {
	return xxx_messageInfo_AddSecurityGroupResponse.Size(m)
}
func (m *AddSecurityGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSecurityGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSecurityGroupResponse proto.InternalMessageInfo

type AddBridgeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBridgeResponse) Reset()         { *m = AddBridgeResponse{} }
func (m *AddBridgeResponse) String() string { return proto.CompactTextString(m) }
func (*AddBridgeResponse) ProtoMessage()    {}
func (*AddBridgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{19}
}

func (m *AddBridgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBridgeResponse.Unmarshal(m, b)
}
func (m *AddBridgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBridgeResponse.Marshal(b, m, deterministic)
}
func (m *AddBridgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBridgeResponse.Merge(m, src)
}
func (m *AddBridgeResponse) XXX_Size() int {
	return xxx_messageInfo_AddBridgeResponse.Size(m)
}
func (m *AddBridgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBridgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBridgeResponse proto.InternalMessageInfo

type AddVLANInterfaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddVLANInterfaceResponse) Reset()         { *m = AddVLANInterfaceResponse{} }
func (m *AddVLANInterfaceResponse) String() string { return proto.CompactTextString(m) }
func (*AddVLANInterfaceResponse) ProtoMessage()    {}
func (*AddVLANInterfaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{20}
}

func (m *AddVLANInterfaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddVLANInterfaceResponse.Unmarshal(m, b)
}
func (m *AddVLANInterfaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddVLANInterfaceResponse.Marshal(b, m, deterministic)
}
func (m *AddVLANInterfaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddVLANInterfaceResponse.Merge(m, src)
}
func (m *AddVLANInterfaceResponse) XXX_Size() int {
	return xxx_messageInfo_AddVLANInterfaceResponse.Size(m)
}
func (m *AddVLANInterfaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddVLANInterfaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddVLANInterfaceResponse proto.InternalMessageInfo

type AddInterfaceToBridgeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddInterfaceToBridgeResponse) Reset()         { *m = AddInterfaceToBridgeResponse{} }
func (m *AddInterfaceToBridgeResponse) String() string { return proto.CompactTextString(m) }
func (*AddInterfaceToBridgeResponse) ProtoMessage()    {}
func (*AddInterfaceToBridgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{21}
}

func (m *AddInterfaceToBridgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddInterfaceToBridgeResponse.Unmarshal(m, b)
}
func (m *AddInterfaceToBridgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddInterfaceToBridgeResponse.Marshal(b, m, deterministic)
}
func (m *AddInterfaceToBridgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddInterfaceToBridgeResponse.Merge(m, src)
}
func (m *AddInterfaceToBridgeResponse) XXX_Size() int {
	return xxx_messageInfo_AddInterfaceToBridgeResponse.Size(m)
}
func (m *AddInterfaceToBridgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddInterfaceToBridgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddInterfaceToBridgeResponse proto.InternalMessageInfo

type AddVirtualMachineResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddVirtualMachineResponse) Reset()         { *m = AddVirtualMachineResponse{} }
func (m *AddVirtualMachineResponse) String() string { return proto.CompactTextString(m) }
func (*AddVirtualMachineResponse) ProtoMessage()    {}
func (*AddVirtualMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{22}
}

func (m *AddVirtualMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddVirtualMachineResponse.Unmarshal(m, b)
}
func (m *AddVirtualMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddVirtualMachineResponse.Marshal(b, m, deterministic)
}
func (m *AddVirtualMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddVirtualMachineResponse.Merge(m, src)
}
func (m *AddVirtualMachineResponse) XXX_Size() int {
	return xxx_messageInfo_AddVirtualMachineResponse.Size(m)
}
func (m *AddVirtualMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddVirtualMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddVirtualMachineResponse proto.InternalMessageInfo

func (m *AddVirtualMachineResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddVirtualMachineResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ConnectBlockDeviceResponse struct {
	DeviceName           string   `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectBlockDeviceResponse) Reset()         { *m = ConnectBlockDeviceResponse{} }
func (m *ConnectBlockDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectBlockDeviceResponse) ProtoMessage()    {}
func (*ConnectBlockDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{23}
}

func (m *ConnectBlockDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectBlockDeviceResponse.Unmarshal(m, b)
}
func (m *ConnectBlockDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectBlockDeviceResponse.Marshal(b, m, deterministic)
}
func (m *ConnectBlockDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectBlockDeviceResponse.Merge(m, src)
}
func (m *ConnectBlockDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectBlockDeviceResponse.Size(m)
}
func (m *ConnectBlockDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectBlockDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectBlockDeviceResponse proto.InternalMessageInfo

func (m *ConnectBlockDeviceResponse) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

type StartVirtualMachineResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartVirtualMachineResponse) Reset()         { *m = StartVirtualMachineResponse{} }
func (m *StartVirtualMachineResponse) String() string { return proto.CompactTextString(m) }
func (*StartVirtualMachineResponse) ProtoMessage()    {}
func (*StartVirtualMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{24}
}

func (m *StartVirtualMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartVirtualMachineResponse.Unmarshal(m, b)
}
func (m *StartVirtualMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartVirtualMachineResponse.Marshal(b, m, deterministic)
}
func (m *StartVirtualMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartVirtualMachineResponse.Merge(m, src)
}
func (m *StartVirtualMachineResponse) XXX_Size() int {
	return xxx_messageInfo_StartVirtualMachineResponse.Size(m)
}
func (m *StartVirtualMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartVirtualMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartVirtualMachineResponse proto.InternalMessageInfo

func (m *StartVirtualMachineResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *StartVirtualMachineResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AttachBlockDeviceResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachBlockDeviceResponse) Reset()         { *m = AttachBlockDeviceResponse{} }
func (m *AttachBlockDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*AttachBlockDeviceResponse) ProtoMessage()    {}
func (*AttachBlockDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{25}
}

func (m *AttachBlockDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachBlockDeviceResponse.Unmarshal(m, b)
}
func (m *AttachBlockDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachBlockDeviceResponse.Marshal(b, m, deterministic)
}
func (m *AttachBlockDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachBlockDeviceResponse.Merge(m, src)
}
func (m *AttachBlockDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_AttachBlockDeviceResponse.Size(m)
}
func (m *AttachBlockDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachBlockDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttachBlockDeviceResponse proto.InternalMessageInfo

func (m *AttachBlockDeviceResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AttachBlockDeviceResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AttachInterfaceResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachInterfaceResponse) Reset()         { *m = AttachInterfaceResponse{} }
func (m *AttachInterfaceResponse) String() string { return proto.CompactTextString(m) }
func (*AttachInterfaceResponse) ProtoMessage()    {}
func (*AttachInterfaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{26}
}

func (m *AttachInterfaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachInterfaceResponse.Unmarshal(m, b)
}
func (m *AttachInterfaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachInterfaceResponse.Marshal(b, m, deterministic)
}
func (m *AttachInterfaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachInterfaceResponse.Merge(m, src)
}
func (m *AttachInterfaceResponse) XXX_Size() int {
	return xxx_messageInfo_AttachInterfaceResponse.Size(m)
}
func (m *AttachInterfaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachInterfaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttachInterfaceResponse proto.InternalMessageInfo

func (m *AttachInterfaceResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AttachInterfaceResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteBridgeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBridgeResponse) Reset()         { *m = DeleteBridgeResponse{} }
func (m *DeleteBridgeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBridgeResponse) ProtoMessage()    {}
func (*DeleteBridgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{27}
}

func (m *DeleteBridgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBridgeResponse.Unmarshal(m, b)
}
func (m *DeleteBridgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBridgeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBridgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBridgeResponse.Merge(m, src)
}
func (m *DeleteBridgeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBridgeResponse.Size(m)
}
func (m *DeleteBridgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBridgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBridgeResponse proto.InternalMessageInfo

type DeleteVLANInterfaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVLANInterfaceResponse) Reset()         { *m = DeleteVLANInterfaceResponse{} }
func (m *DeleteVLANInterfaceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteVLANInterfaceResponse) ProtoMessage()    {}
func (*DeleteVLANInterfaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{28}
}

func (m *DeleteVLANInterfaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVLANInterfaceResponse.Unmarshal(m, b)
}
func (m *DeleteVLANInterfaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVLANInterfaceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteVLANInterfaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVLANInterfaceResponse.Merge(m, src)
}
func (m *DeleteVLANInterfaceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteVLANInterfaceResponse.Size(m)
}
func (m *DeleteVLANInterfaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVLANInterfaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVLANInterfaceResponse proto.InternalMessageInfo

type DeleteInterfaceFromBridgeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteInterfaceFromBridgeResponse) Reset()         { *m = DeleteInterfaceFromBridgeResponse{} }
func (m *DeleteInterfaceFromBridgeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteInterfaceFromBridgeResponse) ProtoMessage()    {}
func (*DeleteInterfaceFromBridgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{29}
}

func (m *DeleteInterfaceFromBridgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteInterfaceFromBridgeResponse.Unmarshal(m, b)
}
func (m *DeleteInterfaceFromBridgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteInterfaceFromBridgeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteInterfaceFromBridgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteInterfaceFromBridgeResponse.Merge(m, src)
}
func (m *DeleteInterfaceFromBridgeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteInterfaceFromBridgeResponse.Size(m)
}
func (m *DeleteInterfaceFromBridgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteInterfaceFromBridgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteInterfaceFromBridgeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetISCSIQualifiedNameRequest)(nil), "agent.GetISCSIQualifiedNameRequest")
	proto.RegisterType((*GetIPTablesRequest)(nil), "agent.GetIPTablesRequest")
	proto.RegisterType((*SetupDefaultSecurityGroupRequest)(nil), "agent.SetupDefaultSecurityGroupRequest")
	proto.RegisterType((*AddSecurityGroupRequest)(nil), "agent.AddSecurityGroupRequest")
	proto.RegisterType((*AddBridgeRequest)(nil), "agent.AddBridgeRequest")
	proto.RegisterType((*AddVLANInterfaceRequest)(nil), "agent.AddVLANInterfaceRequest")
	proto.RegisterType((*AddInterfaceToBridgeRequest)(nil), "agent.AddInterfaceToBridgeRequest")
	proto.RegisterType((*AddVirtualMachineRequest)(nil), "agent.AddVirtualMachineRequest")
	proto.RegisterType((*ConnectBlockDeviceRequest)(nil), "agent.ConnectBlockDeviceRequest")
	proto.RegisterType((*AttachBlockDeviceRequest)(nil), "agent.AttachBlockDeviceRequest")
	proto.RegisterType((*AttachInterfaceRequest)(nil), "agent.AttachInterfaceRequest")
	proto.RegisterType((*StartVirtualMachineRequest)(nil), "agent.StartVirtualMachineRequest")
	proto.RegisterType((*DeleteBridgeRequest)(nil), "agent.DeleteBridgeRequest")
	proto.RegisterType((*DeleteVLANInterfaceRequest)(nil), "agent.DeleteVLANInterfaceRequest")
	proto.RegisterType((*DeleteInterfaceFromBridgeRequest)(nil), "agent.DeleteInterfaceFromBridgeRequest")
	proto.RegisterType((*GetISCSIQualifiedNameResponse)(nil), "agent.GetISCSIQualifiedNameResponse")
	proto.RegisterType((*GetIPTablesResponse)(nil), "agent.GetIPTablesResponse")
	proto.RegisterType((*SetupDefaultSecurityGroupResponse)(nil), "agent.SetupDefaultSecurityGroupResponse")
	proto.RegisterType((*AddSecurityGroupResponse)(nil), "agent.AddSecurityGroupResponse")
	proto.RegisterType((*AddBridgeResponse)(nil), "agent.AddBridgeResponse")
	proto.RegisterType((*AddVLANInterfaceResponse)(nil), "agent.AddVLANInterfaceResponse")
	proto.RegisterType((*AddInterfaceToBridgeResponse)(nil), "agent.AddInterfaceToBridgeResponse")
	proto.RegisterType((*AddVirtualMachineResponse)(nil), "agent.AddVirtualMachineResponse")
	proto.RegisterType((*ConnectBlockDeviceResponse)(nil), "agent.ConnectBlockDeviceResponse")
	proto.RegisterType((*StartVirtualMachineResponse)(nil), "agent.StartVirtualMachineResponse")
	proto.RegisterType((*AttachBlockDeviceResponse)(nil), "agent.AttachBlockDeviceResponse")
	proto.RegisterType((*AttachInterfaceResponse)(nil), "agent.AttachInterfaceResponse")
	proto.RegisterType((*DeleteBridgeResponse)(nil), "agent.DeleteBridgeResponse")
	proto.RegisterType((*DeleteVLANInterfaceResponse)(nil), "agent.DeleteVLANInterfaceResponse")
	proto.RegisterType((*DeleteInterfaceFromBridgeResponse)(nil), "agent.DeleteInterfaceFromBridgeResponse")
}

func init() {
	proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77)
}

var fileDescriptor_56ede974c0020f77 = []byte{
	// 947 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0x6e, 0xda, 0xa4, 0x28, 0xa7, 0x2d, 0x2d, 0xd3, 0x5b, 0xea, 0xde, 0xb2, 0x53, 0xc4, 0xee,
	0xbe, 0xac, 0xb8, 0x3c, 0x23, 0xe1, 0x6d, 0xd9, 0x55, 0x04, 0xac, 0xc0, 0x59, 0xd0, 0x4a, 0x68,
	0x09, 0x13, 0xcf, 0xb4, 0x6b, 0xad, 0x63, 0x7b, 0xed, 0x71, 0xa0, 0xef, 0xfc, 0x1c, 0x7e, 0x12,
	0x3f, 0x06, 0x79, 0x6e, 0xb6, 0x93, 0xb1, 0xa3, 0x4a, 0xf0, 0x16, 0x9f, 0xfb, 0x7c, 0x73, 0xce,
	0x77, 0x26, 0xb0, 0x45, 0xee, 0x58, 0xc4, 0x9f, 0x25, 0x69, 0xcc, 0x63, 0xd4, 0x13, 0x1f, 0xf8,
	0x02, 0xce, 0x5e, 0x32, 0x3e, 0x1a, 0x5f, 0x8f, 0x47, 0x3f, 0xe5, 0x24, 0x0c, 0x6e, 0x03, 0x46,
	0x5f, 0x91, 0x19, 0xf3, 0xd8, 0x87, 0x9c, 0x65, 0x1c, 0x1f, 0x00, 0x2a, 0xf4, 0x3f, 0xbe, 0x26,
	0xd3, 0x90, 0x65, 0x5a, 0x8a, 0x61, 0x38, 0x66, 0x3c, 0x4f, 0x6e, 0xd8, 0x2d, 0xc9, 0x43, 0x3e,
	0x66, 0x7e, 0x9e, 0x06, 0xfc, 0xfe, 0x65, 0x1a, 0xe7, 0x89, 0xb6, 0xf9, 0x03, 0x8e, 0x5d, 0x4a,
	0x6d, 0x2a, 0x74, 0x06, 0xfd, 0x20, 0xe2, 0x2c, 0xbd, 0x25, 0x3e, 0x1b, 0x74, 0x86, 0x9d, 0x27,
	0x7d, 0xaf, 0x14, 0xa0, 0x73, 0x80, 0x20, 0x99, 0x10, 0x4a, 0x53, 0x96, 0x65, 0x83, 0x75, 0xa5,
	0x4e, 0x5c, 0x29, 0x40, 0x97, 0xb0, 0x35, 0x23, 0xbe, 0xd1, 0x6f, 0x08, 0x3d, 0xcc, 0x88, 0xaf,
	0x0c, 0xf0, 0x67, 0xb0, 0xe7, 0x52, 0xfa, 0x3c, 0x0d, 0xe8, 0x9d, 0x3e, 0x06, 0x42, 0xd0, 0x8d,
	0xc8, 0x4c, 0x27, 0x13, 0xbf, 0xf1, 0x5b, 0x51, 0xe0, 0x2f, 0xdf, 0xbb, 0xaf, 0x46, 0x3a, 0xb7,
	0x36, 0x3f, 0x86, 0x8f, 0xe6, 0x21, 0x89, 0x26, 0x01, 0x15, 0x1e, 0x3b, 0xde, 0x66, 0xf1, 0x39,
	0xa2, 0xe8, 0x29, 0xec, 0x25, 0x24, 0x65, 0x11, 0x9f, 0x94, 0x07, 0x90, 0x15, 0xee, 0x4a, 0xb9,
	0x09, 0x85, 0xc7, 0x70, 0xea, 0x52, 0x6a, 0xbe, 0x5f, 0xc7, 0xf5, 0x8a, 0x8e, 0x60, 0x73, 0x2a,
	0x04, 0xaa, 0x26, 0xf5, 0x55, 0xc7, 0x66, 0x7d, 0x01, 0x1b, 0xfc, 0x57, 0x07, 0x06, 0x45, 0xd1,
	0x41, 0xca, 0x73, 0x12, 0xfe, 0x40, 0xfc, 0x77, 0x41, 0xd4, 0x76, 0x48, 0x74, 0x00, 0xbd, 0xb9,
	0x9f, 0xe4, 0x12, 0xc7, 0x1d, 0x4f, 0x7e, 0x14, 0x10, 0xcf, 0xd8, 0x2c, 0x4e, 0xef, 0x27, 0xef,
	0x83, 0xa9, 0x80, 0xb0, 0xeb, 0xf5, 0xa5, 0xe4, 0xbb, 0x60, 0x5a, 0x40, 0x3c, 0x8d, 0x63, 0x3e,
	0xa1, 0x6c, 0x1e, 0xf8, 0x6c, 0xd0, 0x95, 0x10, 0x17, 0xa2, 0x1b, 0x21, 0xc1, 0x6f, 0xe1, 0xe4,
	0x3a, 0x8e, 0x22, 0xe6, 0xf3, 0xe7, 0x61, 0xec, 0xbf, 0x97, 0x52, 0x5d, 0x46, 0x81, 0x51, 0x9c,
	0x72, 0x12, 0xea, 0x3b, 0x62, 0xd9, 0xa0, 0x33, 0xdc, 0x10, 0x18, 0x09, 0xb9, 0xab, 0xc5, 0xe8,
	0x10, 0x36, 0xc3, 0x5c, 0xc0, 0x2c, 0x4f, 0xda, 0x0b, 0xf3, 0x68, 0x44, 0xf1, 0x9f, 0x30, 0x70,
	0x39, 0x27, 0xfe, 0x3b, 0x4b, 0x74, 0x04, 0xdd, 0x3c, 0x57, 0xf7, 0xd2, 0xf7, 0xc4, 0x6f, 0x74,
	0x05, 0x3b, 0x59, 0x9c, 0xa7, 0x3e, 0xd3, 0x15, 0xcb, 0x68, 0xdb, 0x52, 0x28, 0xfd, 0x0b, 0x23,
	0x4e, 0xd2, 0x3b, 0x66, 0x8e, 0x25, 0x3b, 0x67, 0x5b, 0x0a, 0xd5, 0xc1, 0xfe, 0xee, 0xc0, 0x91,
	0x4c, 0xbd, 0xd4, 0x13, 0xb6, 0xc4, 0xe5, 0x25, 0xae, 0xd7, 0x2e, 0xf1, 0x31, 0xec, 0x06, 0xd1,
	0x34, 0xce, 0x23, 0x3a, 0x21, 0x73, 0x96, 0x92, 0x3b, 0x99, 0x6d, 0xc7, 0xfb, 0x58, 0x89, 0x5d,
	0x29, 0x2d, 0xb0, 0x8a, 0x73, 0x5e, 0xb7, 0xec, 0x0a, 0xcb, 0x5d, 0x2d, 0xd7, 0xa6, 0xfa, 0x76,
	0x7b, 0x95, 0x16, 0xfe, 0x1c, 0x9c, 0x31, 0x27, 0x29, 0x6f, 0xec, 0x87, 0xc5, 0x8a, 0xf1, 0x53,
	0xd8, 0xbf, 0x61, 0x21, 0xe3, 0x6c, 0xf5, 0x7c, 0xfc, 0x0e, 0x8e, 0x34, 0xfd, 0xdf, 0x46, 0xe4,
	0x0d, 0x0c, 0x65, 0x06, 0x23, 0x7a, 0x91, 0xc6, 0xb3, 0xff, 0x62, 0x4e, 0xbe, 0x80, 0xf3, 0x06,
	0x5a, 0xcb, 0x92, 0x38, 0xca, 0x18, 0xda, 0x83, 0x8d, 0xe0, 0x43, 0xa4, 0x62, 0x16, 0x3f, 0xf1,
	0x21, 0xec, 0xd7, 0x98, 0x4e, 0x1a, 0xe2, 0x2b, 0x78, 0xd4, 0x42, 0x75, 0xca, 0xc8, 0x11, 0x53,
	0x69, 0xd7, 0xed, 0xc3, 0x27, 0x15, 0x3a, 0xaa, 0x39, 0x2c, 0x00, 0xab, 0x74, 0x17, 0x70, 0x66,
	0x27, 0x0e, 0xa5, 0xbf, 0x86, 0x13, 0x0b, 0x05, 0xa8, 0x73, 0xd9, 0xba, 0x54, 0x5f, 0xee, 0x7a,
	0xe5, 0x72, 0xbf, 0x06, 0xc7, 0x36, 0xc1, 0x2a, 0xca, 0x25, 0x6c, 0xc9, 0x21, 0x99, 0x54, 0xba,
	0x02, 0xa4, 0xa8, 0x80, 0x11, 0x7f, 0x0b, 0xa7, 0xd6, 0xc6, 0x7b, 0x60, 0x15, 0xc5, 0x51, 0x96,
	0x07, 0xfd, 0x81, 0x41, 0x5c, 0x38, 0x5e, 0x1a, 0xd9, 0x07, 0x86, 0x38, 0x82, 0x83, 0xfa, 0x54,
	0x28, 0xa8, 0xcf, 0xe1, 0xd4, 0x3a, 0x02, 0x65, 0x6f, 0xb4, 0xf4, 0xaf, 0x34, 0xfa, 0xf2, 0x1f,
	0x80, 0x9e, 0x5b, 0xec, 0x5a, 0x44, 0xe1, 0xd0, 0xda, 0x94, 0xe8, 0xea, 0x99, 0xdc, 0xcc, 0x6d,
	0x9b, 0xd8, 0xf9, 0xb4, 0xdd, 0x48, 0x95, 0xb4, 0x86, 0x5e, 0xc0, 0x56, 0xa5, 0x8f, 0xd1, 0x49,
	0xc5, 0xad, 0xbe, 0xc5, 0x1d, 0xc7, 0xa6, 0x32, 0x71, 0x12, 0x38, 0x69, 0x6c, 0x7c, 0xf4, 0x58,
	0xb9, 0xae, 0x7a, 0x05, 0x38, 0x4f, 0x56, 0x1b, 0x9a, 0x8c, 0x3f, 0x8b, 0xc5, 0x5d, 0x4f, 0x74,
	0xa1, 0xfc, 0x1b, 0x9e, 0x12, 0xce, 0x65, 0xa3, 0xde, 0x84, 0xfd, 0x06, 0xfa, 0x66, 0x00, 0xd1,
	0x71, 0x69, 0x5f, 0xe3, 0x19, 0x67, 0xb0, 0xac, 0x58, 0x28, 0xac, 0xd6, 0x03, 0xd5, 0xc2, 0x6c,
	0xfc, 0x58, 0x2d, 0xcc, 0xde, 0x3c, 0x6b, 0x88, 0xc0, 0x81, 0x6d, 0xd0, 0x11, 0x2e, 0x5d, 0x9b,
	0x9e, 0x0f, 0xce, 0x55, 0xab, 0x8d, 0x49, 0xf1, 0x46, 0x90, 0x4f, 0x7d, 0x4a, 0x51, 0xb5, 0x34,
	0xdb, 0xe2, 0x70, 0x86, 0xcd, 0x06, 0x26, 0xf2, 0xaf, 0x80, 0x96, 0x09, 0x04, 0x69, 0xcf, 0xc6,
	0xd7, 0x81, 0xf3, 0xa8, 0xc5, 0xc2, 0x04, 0xff, 0x0d, 0xf6, 0x2d, 0xf4, 0x82, 0xb4, 0x6f, 0xf3,
	0xce, 0x73, 0x70, 0x9b, 0x49, 0x0d, 0x96, 0x45, 0xde, 0x29, 0x61, 0x69, 0x78, 0x7a, 0x94, 0xb0,
	0x34, 0x51, 0x16, 0x5e, 0x43, 0x1e, 0xec, 0x2e, 0x90, 0x11, 0x3a, 0xaf, 0xb9, 0x2d, 0x35, 0xca,
	0x45, 0x93, 0xda, 0xc4, 0x1c, 0xc1, 0x76, 0x95, 0x9d, 0x90, 0x9e, 0x5b, 0xcb, 0x22, 0x77, 0x4e,
	0xad, 0xba, 0x2a, 0xb0, 0x16, 0x42, 0x33, 0xc0, 0x36, 0xef, 0x7b, 0x03, 0x6c, 0x1b, 0x1f, 0x0a,
	0xd2, 0x68, 0x64, 0x44, 0x43, 0x1a, 0xab, 0x76, 0xbe, 0x21, 0x8d, 0x95, 0xe4, 0x8a, 0xd7, 0xa6,
	0x9b, 0xe2, 0xef, 0xcc, 0x57, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xc1, 0xab, 0x42, 0xdd,
	0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	GetISCSIQualifiedName(ctx context.Context, in *GetISCSIQualifiedNameRequest, opts ...grpc.CallOption) (*GetISCSIQualifiedNameResponse, error)
	GetIPTables(ctx context.Context, in *GetIPTablesRequest, opts ...grpc.CallOption) (*GetIPTablesResponse, error)
	SetupDefaultSecurityGroup(ctx context.Context, in *SetupDefaultSecurityGroupRequest, opts ...grpc.CallOption) (*SetupDefaultSecurityGroupResponse, error)
	AddSecurityGroup(ctx context.Context, in *AddSecurityGroupRequest, opts ...grpc.CallOption) (*AddSecurityGroupResponse, error)
	AddBridge(ctx context.Context, in *AddBridgeRequest, opts ...grpc.CallOption) (*AddBridgeResponse, error)
	AddVLANInterface(ctx context.Context, in *AddVLANInterfaceRequest, opts ...grpc.CallOption) (*AddVLANInterfaceResponse, error)
	AddInterfaceToBridge(ctx context.Context, in *AddInterfaceToBridgeRequest, opts ...grpc.CallOption) (*AddInterfaceToBridgeResponse, error)
	AddVirtualMachine(ctx context.Context, in *AddVirtualMachineRequest, opts ...grpc.CallOption) (*AddVirtualMachineResponse, error)
	ConnectBlockDevice(ctx context.Context, in *ConnectBlockDeviceRequest, opts ...grpc.CallOption) (*ConnectBlockDeviceResponse, error)
	StartVirtualMachine(ctx context.Context, in *StartVirtualMachineRequest, opts ...grpc.CallOption) (*StartVirtualMachineResponse, error)
	AttachBlockDevice(ctx context.Context, in *AttachBlockDeviceRequest, opts ...grpc.CallOption) (*AttachBlockDeviceResponse, error)
	AttachInterface(ctx context.Context, in *AttachInterfaceRequest, opts ...grpc.CallOption) (*AttachInterfaceResponse, error)
	DeleteBridge(ctx context.Context, in *DeleteBridgeRequest, opts ...grpc.CallOption) (*DeleteBridgeResponse, error)
	DeleteVLANInterface(ctx context.Context, in *DeleteVLANInterfaceRequest, opts ...grpc.CallOption) (*DeleteVLANInterfaceResponse, error)
	DeleteInterfaceFromBridge(ctx context.Context, in *DeleteInterfaceFromBridgeRequest, opts ...grpc.CallOption) (*DeleteInterfaceFromBridgeResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) GetISCSIQualifiedName(ctx context.Context, in *GetISCSIQualifiedNameRequest, opts ...grpc.CallOption) (*GetISCSIQualifiedNameResponse, error) {
	out := new(GetISCSIQualifiedNameResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/GetISCSIQualifiedName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetIPTables(ctx context.Context, in *GetIPTablesRequest, opts ...grpc.CallOption) (*GetIPTablesResponse, error) {
	out := new(GetIPTablesResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/GetIPTables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SetupDefaultSecurityGroup(ctx context.Context, in *SetupDefaultSecurityGroupRequest, opts ...grpc.CallOption) (*SetupDefaultSecurityGroupResponse, error) {
	out := new(SetupDefaultSecurityGroupResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/SetupDefaultSecurityGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) AddSecurityGroup(ctx context.Context, in *AddSecurityGroupRequest, opts ...grpc.CallOption) (*AddSecurityGroupResponse, error) {
	out := new(AddSecurityGroupResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/AddSecurityGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) AddBridge(ctx context.Context, in *AddBridgeRequest, opts ...grpc.CallOption) (*AddBridgeResponse, error) {
	out := new(AddBridgeResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/AddBridge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) AddVLANInterface(ctx context.Context, in *AddVLANInterfaceRequest, opts ...grpc.CallOption) (*AddVLANInterfaceResponse, error) {
	out := new(AddVLANInterfaceResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/AddVLANInterface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) AddInterfaceToBridge(ctx context.Context, in *AddInterfaceToBridgeRequest, opts ...grpc.CallOption) (*AddInterfaceToBridgeResponse, error) {
	out := new(AddInterfaceToBridgeResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/AddInterfaceToBridge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) AddVirtualMachine(ctx context.Context, in *AddVirtualMachineRequest, opts ...grpc.CallOption) (*AddVirtualMachineResponse, error) {
	out := new(AddVirtualMachineResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/AddVirtualMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ConnectBlockDevice(ctx context.Context, in *ConnectBlockDeviceRequest, opts ...grpc.CallOption) (*ConnectBlockDeviceResponse, error) {
	out := new(ConnectBlockDeviceResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/ConnectBlockDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StartVirtualMachine(ctx context.Context, in *StartVirtualMachineRequest, opts ...grpc.CallOption) (*StartVirtualMachineResponse, error) {
	out := new(StartVirtualMachineResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/StartVirtualMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) AttachBlockDevice(ctx context.Context, in *AttachBlockDeviceRequest, opts ...grpc.CallOption) (*AttachBlockDeviceResponse, error) {
	out := new(AttachBlockDeviceResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/AttachBlockDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) AttachInterface(ctx context.Context, in *AttachInterfaceRequest, opts ...grpc.CallOption) (*AttachInterfaceResponse, error) {
	out := new(AttachInterfaceResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/AttachInterface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteBridge(ctx context.Context, in *DeleteBridgeRequest, opts ...grpc.CallOption) (*DeleteBridgeResponse, error) {
	out := new(DeleteBridgeResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/DeleteBridge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteVLANInterface(ctx context.Context, in *DeleteVLANInterfaceRequest, opts ...grpc.CallOption) (*DeleteVLANInterfaceResponse, error) {
	out := new(DeleteVLANInterfaceResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/DeleteVLANInterface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteInterfaceFromBridge(ctx context.Context, in *DeleteInterfaceFromBridgeRequest, opts ...grpc.CallOption) (*DeleteInterfaceFromBridgeResponse, error) {
	out := new(DeleteInterfaceFromBridgeResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/DeleteInterfaceFromBridge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	GetISCSIQualifiedName(context.Context, *GetISCSIQualifiedNameRequest) (*GetISCSIQualifiedNameResponse, error)
	GetIPTables(context.Context, *GetIPTablesRequest) (*GetIPTablesResponse, error)
	SetupDefaultSecurityGroup(context.Context, *SetupDefaultSecurityGroupRequest) (*SetupDefaultSecurityGroupResponse, error)
	AddSecurityGroup(context.Context, *AddSecurityGroupRequest) (*AddSecurityGroupResponse, error)
	AddBridge(context.Context, *AddBridgeRequest) (*AddBridgeResponse, error)
	AddVLANInterface(context.Context, *AddVLANInterfaceRequest) (*AddVLANInterfaceResponse, error)
	AddInterfaceToBridge(context.Context, *AddInterfaceToBridgeRequest) (*AddInterfaceToBridgeResponse, error)
	AddVirtualMachine(context.Context, *AddVirtualMachineRequest) (*AddVirtualMachineResponse, error)
	ConnectBlockDevice(context.Context, *ConnectBlockDeviceRequest) (*ConnectBlockDeviceResponse, error)
	StartVirtualMachine(context.Context, *StartVirtualMachineRequest) (*StartVirtualMachineResponse, error)
	AttachBlockDevice(context.Context, *AttachBlockDeviceRequest) (*AttachBlockDeviceResponse, error)
	AttachInterface(context.Context, *AttachInterfaceRequest) (*AttachInterfaceResponse, error)
	DeleteBridge(context.Context, *DeleteBridgeRequest) (*DeleteBridgeResponse, error)
	DeleteVLANInterface(context.Context, *DeleteVLANInterfaceRequest) (*DeleteVLANInterfaceResponse, error)
	DeleteInterfaceFromBridge(context.Context, *DeleteInterfaceFromBridgeRequest) (*DeleteInterfaceFromBridgeResponse, error)
}

// UnimplementedAgentServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (*UnimplementedAgentServer) GetISCSIQualifiedName(ctx context.Context, req *GetISCSIQualifiedNameRequest) (*GetISCSIQualifiedNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetISCSIQualifiedName not implemented")
}
func (*UnimplementedAgentServer) GetIPTables(ctx context.Context, req *GetIPTablesRequest) (*GetIPTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIPTables not implemented")
}
func (*UnimplementedAgentServer) SetupDefaultSecurityGroup(ctx context.Context, req *SetupDefaultSecurityGroupRequest) (*SetupDefaultSecurityGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupDefaultSecurityGroup not implemented")
}
func (*UnimplementedAgentServer) AddSecurityGroup(ctx context.Context, req *AddSecurityGroupRequest) (*AddSecurityGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSecurityGroup not implemented")
}
func (*UnimplementedAgentServer) AddBridge(ctx context.Context, req *AddBridgeRequest) (*AddBridgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBridge not implemented")
}
func (*UnimplementedAgentServer) AddVLANInterface(ctx context.Context, req *AddVLANInterfaceRequest) (*AddVLANInterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVLANInterface not implemented")
}
func (*UnimplementedAgentServer) AddInterfaceToBridge(ctx context.Context, req *AddInterfaceToBridgeRequest) (*AddInterfaceToBridgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddInterfaceToBridge not implemented")
}
func (*UnimplementedAgentServer) AddVirtualMachine(ctx context.Context, req *AddVirtualMachineRequest) (*AddVirtualMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVirtualMachine not implemented")
}
func (*UnimplementedAgentServer) ConnectBlockDevice(ctx context.Context, req *ConnectBlockDeviceRequest) (*ConnectBlockDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectBlockDevice not implemented")
}
func (*UnimplementedAgentServer) StartVirtualMachine(ctx context.Context, req *StartVirtualMachineRequest) (*StartVirtualMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVirtualMachine not implemented")
}
func (*UnimplementedAgentServer) AttachBlockDevice(ctx context.Context, req *AttachBlockDeviceRequest) (*AttachBlockDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachBlockDevice not implemented")
}
func (*UnimplementedAgentServer) AttachInterface(ctx context.Context, req *AttachInterfaceRequest) (*AttachInterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachInterface not implemented")
}
func (*UnimplementedAgentServer) DeleteBridge(ctx context.Context, req *DeleteBridgeRequest) (*DeleteBridgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBridge not implemented")
}
func (*UnimplementedAgentServer) DeleteVLANInterface(ctx context.Context, req *DeleteVLANInterfaceRequest) (*DeleteVLANInterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVLANInterface not implemented")
}
func (*UnimplementedAgentServer) DeleteInterfaceFromBridge(ctx context.Context, req *DeleteInterfaceFromBridgeRequest) (*DeleteInterfaceFromBridgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInterfaceFromBridge not implemented")
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_GetISCSIQualifiedName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetISCSIQualifiedNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetISCSIQualifiedName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/GetISCSIQualifiedName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetISCSIQualifiedName(ctx, req.(*GetISCSIQualifiedNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetIPTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetIPTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/GetIPTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetIPTables(ctx, req.(*GetIPTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SetupDefaultSecurityGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupDefaultSecurityGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SetupDefaultSecurityGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/SetupDefaultSecurityGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SetupDefaultSecurityGroup(ctx, req.(*SetupDefaultSecurityGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_AddSecurityGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSecurityGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AddSecurityGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/AddSecurityGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AddSecurityGroup(ctx, req.(*AddSecurityGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_AddBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AddBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/AddBridge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AddBridge(ctx, req.(*AddBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_AddVLANInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVLANInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AddVLANInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/AddVLANInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AddVLANInterface(ctx, req.(*AddVLANInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_AddInterfaceToBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddInterfaceToBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AddInterfaceToBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/AddInterfaceToBridge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AddInterfaceToBridge(ctx, req.(*AddInterfaceToBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_AddVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AddVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/AddVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AddVirtualMachine(ctx, req.(*AddVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ConnectBlockDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectBlockDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ConnectBlockDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/ConnectBlockDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ConnectBlockDevice(ctx, req.(*ConnectBlockDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StartVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StartVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/StartVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StartVirtualMachine(ctx, req.(*StartVirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_AttachBlockDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachBlockDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AttachBlockDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/AttachBlockDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AttachBlockDevice(ctx, req.(*AttachBlockDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_AttachInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AttachInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/AttachInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AttachInterface(ctx, req.(*AttachInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/DeleteBridge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteBridge(ctx, req.(*DeleteBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteVLANInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVLANInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteVLANInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/DeleteVLANInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteVLANInterface(ctx, req.(*DeleteVLANInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteInterfaceFromBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInterfaceFromBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteInterfaceFromBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/DeleteInterfaceFromBridge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteInterfaceFromBridge(ctx, req.(*DeleteInterfaceFromBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetISCSIQualifiedName",
			Handler:    _Agent_GetISCSIQualifiedName_Handler,
		},
		{
			MethodName: "GetIPTables",
			Handler:    _Agent_GetIPTables_Handler,
		},
		{
			MethodName: "SetupDefaultSecurityGroup",
			Handler:    _Agent_SetupDefaultSecurityGroup_Handler,
		},
		{
			MethodName: "AddSecurityGroup",
			Handler:    _Agent_AddSecurityGroup_Handler,
		},
		{
			MethodName: "AddBridge",
			Handler:    _Agent_AddBridge_Handler,
		},
		{
			MethodName: "AddVLANInterface",
			Handler:    _Agent_AddVLANInterface_Handler,
		},
		{
			MethodName: "AddInterfaceToBridge",
			Handler:    _Agent_AddInterfaceToBridge_Handler,
		},
		{
			MethodName: "AddVirtualMachine",
			Handler:    _Agent_AddVirtualMachine_Handler,
		},
		{
			MethodName: "ConnectBlockDevice",
			Handler:    _Agent_ConnectBlockDevice_Handler,
		},
		{
			MethodName: "StartVirtualMachine",
			Handler:    _Agent_StartVirtualMachine_Handler,
		},
		{
			MethodName: "AttachBlockDevice",
			Handler:    _Agent_AttachBlockDevice_Handler,
		},
		{
			MethodName: "AttachInterface",
			Handler:    _Agent_AttachInterface_Handler,
		},
		{
			MethodName: "DeleteBridge",
			Handler:    _Agent_DeleteBridge_Handler,
		},
		{
			MethodName: "DeleteVLANInterface",
			Handler:    _Agent_DeleteVLANInterface_Handler,
		},
		{
			MethodName: "DeleteInterfaceFromBridge",
			Handler:    _Agent_DeleteInterfaceFromBridge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
